name: 'Kubernetes Secret Updater'
description: 'GitHub Action to update a value in a Kubernetes secret.'
author: 'Punit kashyap'
branding:
  icon: 'settings'
  color: 'blue'

outputs:
  message:
    description: 'Confirmation message after updating the secret value'

runs:
  using: 'docker'
  image: 'Dockerfile'
