name: 'Kubernetes Secret Updater'
description: 'GitHub Action to update a value in a Kubernetes secret.'
author: 'Punit kashyap'
branding:
  icon: 'settings'
  color: 'blue'
inputs:
  namespace:
    description: 'Namespace where the secret exists'
    required: true
  secret_name:
    description: 'Name of the secret to be updated'
    required: true
  key:
    description: 'Key of the value in the secret to be updated'
    required: true
  new_value:
    description: 'New value to be set'
    required: true
runs:
  using: 'node16'
  main: 'update-secret.js'
