name: Update Kubernetes Secret Value
description: Updates a value in a Kubernetes secret
inputs:
  namespace:
    description: 'Namespace where the secret exists'
    required: true
  secret_name:
    description: 'Name of the secret to be updated'
    required: true
  key:
    description: 'Key of the value in the secret to be updated'
    required: true
  new_value:
    description: 'New value to be set'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
