name: Publish to Marketplace

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install js-yaml
        run: npm install js-yaml
      
      - name: Install module
        run: npm install dotenv
      
      - name: Install module
        run: npm install @kubernetes/client-node

      - name: Publish to Marketplace
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const actionYml = yaml.load(fs.readFileSync('action.yml', 'utf8'));
            const metadata = {
              name: actionYml.name,
              description: actionYml.description,
              author: actionYml.author,
              inputs: actionYml.inputs,
            };
            console.log(JSON.stringify(metadata));
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
